version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash run.sh
    ports:
      - "7755:7755"
    volumes:
      - /home/sri/fyle-interview-intern-backend:/fyle-interview-intern-backend  # Use the absolute path
    environment:
      - FLASK_APP=core/server.py
