name: Python Tests

on:
    push:
      branches:
        - main
      paths-ignore:
        - 'README.md'
  
permissions:
    id-token: write
    contents: read
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version you need, e.g., '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install your project's dependencies

      - name: Run pytest with coverage
        run: |
          pytest --cov  # Replace 'your_package_name' with the actual package name
